[#5] [UI] As a user, I can see a Progress HUD
markgravity/kmm-ic pull request #57
Opened 2023-04-13 04:23 UTC by markgravity

https://github.com/markgravity/kmm-ic/issues/5

## What happened 👀

- Add Progress HUD UI

## Insight 📝

Please check `ProgressHUD_Previews` to have a better insight into the final result

## Proof Of Work 📹

![CleanShot 2023-04-13 at 11 19 02](https://user-images.githubusercontent.com/17875522/231652437-1f23ec87-cab2-419c-bc37-ff9e668b5ad4.png)

2023-04-13 06:00 UTC, phongvhd93 approved these changes

2023-04-13 10:18 UTC, suho requested changes

2023-04-13 10:18 UTC, suho commented on .github/workflows/deploy_production_appstore.yml
> +name: Deploy Staging Build To Firebase
Why UI tasks but have 2 new workflows?

2023-04-13 10:18 UTC, suho commented on ios/KMMIC/Resources/Assets/Assets.xcassets/AppBackground.imageset/AppBackground.png
Same with these new files, it's not related to the scope of the task

2023-04-14 00:19 UTC, markgravity commented on .github/workflows/deploy_production_appstore.yml
> +name: Deploy Staging Build To Firebase
@suho I rebased the branch 🙏

2023-04-14 00:19 UTC, markgravity commented on ios/KMMIC/Resources/Assets/Assets.xcassets/AppBackground.imageset/AppBackground.png
@suho I rebased the branch 🙏

2023-04-14 08:42 UTC, suho approved these changes

2023-04-14 09:18 UTC, merged